import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :live_view_studio, LiveViewStudioWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json"

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Finch, finch_name: LiveViewStudio.Finch

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
LiveViewStudioWeb
config :blog, LiveViewStudioWeb.Endpoint,
  url: [
    host: "portfolio-app.makoto-developer.net",
    port: System.get_env("APP_PORT_NOT_CERT") || "80"
  ],
  https: [
    port: ,System.get_env("APP_PORT") || "433",
    cipher_suite: :strong,
    certfile: Path.expand("priv/cert/certificate.crt"),
    keyfile: Path.expand("priv/cert/private.key"),
    cacertfile: Path.expand("priv/cert/ca_bundle.crt")
  ],
  force_ssl: [hsts: true]

